config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock'
  }

  devise_scope :user do
    root to: 'devise/sessions#new', as: :login
    get 'sign_in', to: 'devise/sessions#new'
    get 'secret', to: 'devise/passwords#new'
    get 'unlock', to: 'devise/unlocks#new'
    get 'verification', to: 'devise/confirmations#new'
    get 'signup', to: 'devise/registrations#new'
  end

  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_create :update_post_comments_counter
  after_destroy :update_post_comments_counter

  private

  def update_post_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_create :update_post_likes_counter
  after_destroy :update_post_likes_counter

  private

  def update_post_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  after_create :update_user_posts_counter
  after_destroy :update_user_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :body, presence: true, length: { maximum: 1000 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :confirmable, :recoverable

  # has_one_attached :photo
  has_many :likes, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  private

  def assign_name_from_email
    self.name ||= email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?
  def after_sign_in_path_for(_resource)
    users_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :name, :photo, :bio, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:email, :name, :photo, :bio, :password, :current_password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(current_user, @post)
    else
      render 'new'
    end
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.create(author: current_user, post: @post)

    if @like.persisted?
      flash[:success] = 'Liked successfully!'
      redirect_to user_post_path(current_user, @post)
    else
      flash[:alert] = 'Something went wrong'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_posts_path(current_user)

    else
      flash[:alert] = 'Something went wrong'
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h2>Add a Comment</h2>

<%= form_with(model: @comment, url: user_post_comments_path(@post), local: true) do |form| %>

  <div class='comment-input'>
    <%= form.label :text %>
    <%= form.text_area :text, placeholder: 'Enter your comment', class: 'comment-area' %>
    <%= form.submit 'Add Comment', class: 'comment-btn' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <header>

<% if current_user %>
  <%= link_to "New Post", new_user_post_path(current_user) %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% end %>

  

  <body>
      <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="wrapper">
  <div class="userNameWrapper">
          <div><img alt="Profile P."/></div>
          <div class="userName">
              <h2>
                  Name: <%= @user.name %>
              </h2>
              <h6>Number of posts: <%= @user.posts.count%></h6>
          </div>
      </div>

  <% @posts.each_with_index do |post, index| %>

    <div class="post">
      <%= link_to user_post_path(@user, post), class: 'post-link' do %>

        <h2>Post #<%= index+1 %></h2>
        <h3><%= post.title %></h3>
        <p>
        <%= post.body %>
        <br/>

        <div class="count">
          Comments: <%= post.comments.count%>&nbsp;&nbsp;
          likes: <%= post.likes.count%>
        </div>
        </p>
      <% end %>
    </div>
    <% if post.comments.count > 0 %>
      <div class="comments">
        <ul>
            <% post.recent_comments.each do |comment| %>
                <li><%= comment.author.name %>: <%= comment.text %></li>
            <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

  <div class="button">
    <button>Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<h2>Create a Post</h2>

<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :post do |form| %>

  <div class='post-input'>
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: 'Enter title', class: 'post-title' %>
    <%= form.label :body %>
    <%= form.text_area :body, placeholder: 'Enter your post', class: 'post-area' %>
    <%= form.submit 'Create Post', class: 'post-btn' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="wrapper">
  <div class="post">
    <div class="postHeader">
      <h2>Post #<%= @user.posts.index(@post) + 1 %> by <%= @user.name %></h2>
      <h6>Comments: <%= @post.comments.count %>,&nbsp;Likes: <%= @post.likes.count %></h6>
    </div>
    <div class='buttons'>
        <button class='create-comment-btn'>
          <%= link_to 'Add New Comment', new_user_post_comment_path(@user, @post)%>
        </button>

        <div>
          <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |form| %>
            <%= form.submit 'Like Post', class: 'like-btn' %>
          <% end %>
        </div>
    </div>
    <h3><%= @post.title %></h3>
    <p><%= @post.text %></p>
  </div>

  <% if @comments.count > 0 %>
    <div class="comments">
      <ul> 
        <% @comments.each do |comment|%>
            <li><%= comment.author.name %>: <%= comment.text %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
</div>

app/views/users/index.html.erb
<div class="wrapper">
  <ul>
    <% @users.each do |user| %>
      <li class="userNameWrapper">
          <div><img alt="Profile P." src="<%= user.photo %>"/></div>

            <div class="userName">
          <%= link_to user_path(user), class: 'userNameAnchor' do %>
            <h2><%= user.name %></h2>
            <h6>Number of posts: <%= user.posts.count %></h6>
          <% end %>
            </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <div class="userNameWrapper">
    <div><img alt="Profile P." src="<%= @user.photo %>"/></div>
    <div class="userName">
      <h2>Name: <%= @user.name %></h2>
      <h6>Number of posts: <%= @user.posts.count %></h6>
    </div>
  </div>

  <div class="bio">
    <h3>Bio:</h3>
    <p><%= @user.bio %></p>
  </div>

  <% @user.recent_posts.each_with_index do |post, index| %>
    <ul class="post" style="<%= index >= 3 ? 'display:none' : '' %>">
      <li>
        <%= link_to "Post ##{post.id}", user_post_path(@user, post), class: 'user-link' %>
        <% if post.body %>
          <% words = post.body.split %>
          <% if words.length <= 18 %>
            <p><%= post.body %></p>
          <% else %>
            <p><%= words.take(18).join(' ') %>...</p>
          <% end %>
        <% end %>
        <div class="count">
          Comments: <%= post.comments.count %> &nbsp;&nbsp;
          Likes: <%= post.likes.count %>
        </div>
      </li>
    </ul>
  <% end %>

  <div class="button">
    <%= link_to 'See all posts', user_posts_path(@user), id: 'all-posts-link' %>
  </div>
</div>